### PR TITLE
Add object model for ImageQualityIndicators

### PR DESCRIPTION
**Pull request by rjgildea**
Add a `dc.image_quality` to `ispyb.model.data_collection.DataCollection` which returns an `ImageQualityIndicatorsList` object. This can then be iterated over to obtain the individual `ImageQualityIndicators` object corresponding to the database entry for each image.

### CODE REVIEW

**Review by Anthchirp — COMMENTED** [review]
What do `method1_res` and `method2_res` in the database actually stand for? I note that in dlstbx we always write the same value to both columns. Does it make sense to expose both values is the API or should we move to looking at only one of them and completely ignore the other? (Like we do for the `programid` column, which we fill with dummy values)

@KarlLevik will probably know more about the intended use of the columns.

**Comment by rjgildea** [comment]
These are named after "Method 1" and "Method 2" in section _2.4.4. Diffraction resolution_ in the distl paper, see:
https://journals.iucr.org/j/issues/2006/01/00/ea5046/index.html

Both methods of resolution estimation are calculated by the DIALS per-image analysis:
https://github.com/dials/dials/blob/f6996c317ed507ee4aca8c75883cbf37d6a9cb7c/algorithms/spot_finding/per_image_analysis.py#L680-L695

**Comment by Anthchirp** [comment]
Okay. We discard both.
```python
params["method1_res"] = parameters("estimated_d_min")                                                           
params["method2_res"] = parameters("estimated_d_min")                                                           
```

**Comment by rjgildea** [comment]
Although we actually store neither of these numbers in ISPyB, but a 3rd number, "estimated_d_min":
https://gitlab.diamond.ac.uk/scisoft/mx/dlstbx/blob/master/services/ispybsvc.py#L323-324

**Review by Anthchirp — APPROVED** [review]
looks good to me

**Pull request merged**
