### PR TITLE
Add catalog-info for dev portal

### PR DESCRIPTION
**Pull request by rjgildea**

### CODE REVIEW

**Comment by rjgildea** [comment]
@garryod the [catalog import tool](https://dev-portal.diamond.ac.uk/catalog-import) is returning the following error, but it's not obvious to me what it means:
```
{"error":{"name":"NotAllowedError","message":"This operation not allowed in readonly mode"},"request":{"method":"POST","url":"/locations"},"response":{"statusCode":403}}
```

**Comment by garryod** [comment]
> @garryod the [catalog import tool](https://dev-portal.diamond.ac.uk/catalog-import) is returning the following error, but it's not obvious to me what it means:
> 
> ```
> {"error":{"name":"NotAllowedError","message":"This operation not allowed in readonly mode"},"request":{"method":"POST","url":"/locations"},"response":{"statusCode":403}}
> ```

Yes, it will do this. The import functionality is disabled as we want to force all entries to be made via a discovery agent (i.e. from a `catalog-info.yaml` in a git repo). I should at some point re-work the front end to reflect that it only serves as a validation utility.

**Review by garryod — CHANGES_REQUESTED** [review]
It would be good to replace the link with an `diamond.ac.uk/viewdocs-url` entry in `metadata.annotations`. This will embed them as an `<iframe>` in the dev portal 'Docs' tab. 
A human readable name in the `metadata.title` would also be good.

**Review by garryod — APPROVED** [review]
LGTM

**Pull request merged**
