### PR TITLE
Authorisation for relevant methods

### PR DESCRIPTION
**Pull request by KarlLevik**
Changes to support optional authorisation for relevant methods.

- "v2" of relevant SQL routines to support optional authorisation 
- Some SQL functions replaced by procedures 
- `auth_login` parameter (the username) for the Python methods corresponding to the SQL routines
- **Breaking change:** Note that the `retrieve_proposal_title` method now returns a result set (list of tuples) similar to other "retrieve" methods. 

Also, unrelated: modification of method & sproc `update_container_assign` to return the `containerId` and (new) `containerStatus` of the container found.

### CODE REVIEW

**Comment by Anthchirp** [comment]
fundamental question: Are you planning to support the unauthorized methods going forward?

**Comment by KarlLevik** [comment]
> fundamental question: Are you planning to support the unauthorized methods going forward?

Yes! The plan is to keep the unauthorised methods, but make some of them optionally authorised as seen in this PR. Going forward we'll probably also get some new methods which will have mandatory authorisation.

**Comment by Anthchirp** [comment]
In that case would it make sense to use `_auth`/`_authd` (or similar) as a procedure name suffix instead of `_v2`?

**Comment by KarlLevik** [comment]
How about adding `auth` in the name for the procedures with mandatory authorisation? 

We also have the `auth_login` parameter name.

This way we can distinguish between optionally and mandatory authorised procedures - the optionally authorised ones only have the parameter, whereas the ones with mandatory authorisation will also have `auth` in the procedure name. 

We still need to use `v2`, `v3` and so forth in the procedure name whenever the signature changes. Unfortunately, we also need to consider the procedure name length restriction (64 chars).

**Review by Anthchirp — APPROVED** [review]

**Pull request merged**
